### ISSUE TITLE
support AS >=0.20.0

### ISSUE THREAD

**Issue by ianhe8x** [Web3-API/as-bigint#9]
Hi, 
I'm having the following error when import as-bigint into my project, using assemblyscript 0.27.0
```
ERROR TS6054: File '~lib/as-bigint.ts' not found. 
1 │ import { BigInt } from "as-bigint"
   │                        ~~~~~~~~~~~
```
And it works well when I downgrade as to 0.19.23

**Comment by ramilexe** [comment]
@ianhe8x what error do you get when use assemblyscript 0.27.0?

**Comment by ianhe8x** [comment]
@ramilexe sorry, that's accidentally removed from my issue. It's 
`ERROR TS6054: File '~lib/as-bigint.ts' not found.`

**Comment by MaxGraey** [comment]
Try this `import { BigInt } from "as-bigint/assembly"`

**Comment by ianhe8x** [comment]
This works. Thanks for the help.
